apiVersion: v1
kind: ConfigMap
metadata:
  name: enterprise-project-config
  namespace: enterprise-dev
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_LISTENER_AUTO_STARTUP: "true"
  NOTIFICATION_SERVICE_URL: http://notification-service:8081/notifications
