apiVersion: v1
kind: Service
metadata:
  name: enterprise-project
  namespace: enterprise-dev
spec:
  selector:
    app: enterprise-project
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
