spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: enterprise-user-consumer-dev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.enterprise.demo.event"
        spring.json.value.default.type: "com.enterprise.demo.event.UserEvent"
    admin:
      fail-fast: false
      properties:
        request.timeout.ms: 3000
    listener:
      auto-startup: false

notification:
  service:
    url: http://localhost:8081/notifications

logging:
  level:
    org.springframework.web: DEBUG
    com.enterprise.demo: DEBUG
