spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/enterprise_prod
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  kafka:
    consumer:
      group-id: enterprise-user-consumer

logging:
  level:
    root: WARN
    com.enterprise.demo: INFO
