apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: enterprise-dev
spec:
  selector:
    app: notification-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
